#
# Docker setups to test and develop this application.
#
# Build and run all tests via docker-compose up test
version: "3.0"
services:
  test:
    build: .
    volumes:
    - .:/code:z
    working_dir: /code
    entrypoint: /bin/sh
    command: -c 'pip install tox && tox ${TOXARGS}'

  simple:
    build: .
    hostname: simple
    volumes:
    - .:/code
    ports:
    - "8080:8080"
    - "8443:8443"
    command: []
