#
# Questo e' un progetto d'esempio in formato OpenAPI 3.0 API Starter Kit.
#
# Stai per sviluppare un API? Segui attentamente questo template e
#   potrai integrarla facilmente in Developers Italia.
#
x-commons:
  common-responses: &common-responses
    '400':
      $ref: '#/components/responses/400BadRequest'
    '429':
      $ref: '#/components/responses/429TooManyRequests'
    '503':
      $ref: '#/components/responses/503ServiceUnavailable'
    default:
      $ref: '#/components/responses/default'

openapi: 3.0.1
info:
  title: iPA unofficial.
  version: 0rc1
  x-summary: 'Informazioni su Amministrazioni, Uffici ed AOO.'
  contact:
    email: robipolli@gmail.com
    name: Roberto Polli
    url: 'https://twitter.com/ioggstream'
  description: >
    #### Documentazione

    Il servizio permette di interrogare indicePA richiedendo informazioni
    sui singoli enti, uffici ed aree organizzative omogenee.

    L'API permette di selezionare i campi da recuperare ed i campi su cui filtrare,
    ritornando un formato dei dati coerente.


    ##### Sottosezioni

    E' possibile utilizzare - con criterio - delle sottosezioni.


    #### Note


    Il servizio non richiede autenticazione, ma va' usato rispettando gli

    header di throttling esposti in conformita' alle Linee Guida del Modello di
    interoperabilita'.


    #### Informazioni tecniche ed esempi


    Esempio:


    ```

    http http://localhost:8443/ipa/v1/amministrazione/c_e472


    ```
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  termsOfService: 'http://swagger.io/terms/'
  x-api-id: 00000000-0000-0000-0000-000000000000
  x-audience:
    - public
servers:
  - description: Development server
    url: 'https://localhost:8443/ipa/v0'
  - description: Test server
    url: 'https://api.example.com/ipa/v0'
tags:
  - description: Retrieve informations
    externalDocs:
      url: 'http://docs.my-api.com/pet-operations.htm'
    name: public
paths:
  /status:
    get:
      operationId: api.status
      responses:
        <<: *common-responses
        200:
          description: |
            L'API funziona correttamente.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'

  /amministrazioni:
    get:
      operationId: api.list_amministrazioni
      parameters:
        - in: query
          name: codice_ipa
          schema:
            type: string
        - in: query
          name: codice_fiscale
          schema:
            type: string
        - in: query
          name: descrizione
          schema:
            type: string
        - in: query
          name: mail
          schema:
            type: string
        - $ref: 'https://teamdigitale.github.io/openapi/parameters/v3.yaml#/fields'
        - $ref: https://teamdigitale.github.io/openapi/parameters/v3.yaml#/limit
      responses:
        <<: *common-responses
        '200':
          description: foo
          content:
            application/json:
              schema:
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Amministrazione'
  '/amministrazione/{codice_ipa}':
    get:
      operationId: api.get_amministrazione
      parameters:
        - in: path
          name: codice_ipa
          required: true
          schema:
            type: string
        - $ref: 'https://teamdigitale.github.io/openapi/parameters/v3.yaml#/fields'
        - $ref: https://teamdigitale.github.io/openapi/parameters/v3.yaml#/limit

      responses:
        <<: *common-responses
        '200':
          description: bar
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Amministrazione'
  /amministrazione/{codice_ipa}/uffici:
    get:
      operationId: api.get_uffici_by_ipa
      parameters:
        - in: path
          name: codice_ipa
          required: true
          schema:
            type: string
        - in: query
          name: codice_univoco_ufficio
          schema:
            type: string
        - in: query
          name: codice_fiscale
          schema:
            type: string
        - in: query
          name: descrizione
          schema:
            type: string
        - in: query
          name: mail
          schema:
            type: string
        - $ref: 'https://teamdigitale.github.io/openapi/parameters/v3.yaml#/fields'
        - $ref: 'https://teamdigitale.github.io/openapi/parameters/v3.yaml#/limit'
      responses:
        <<: *common-responses
        '200':
          description: foo
          content:
            application/json:
              schema:
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Ufficio'
  /amministrazione/{codice_ipa}/ufficio/{codice_univoco_ufficio}:
    get:
      operationId: api.get_ufficio_by_ipa
      parameters:
        - in: path
          name: codice_ipa
          schema:
            type: string
          required: true
        - in: path
          name: codice_univoco_ufficio
          schema:
            type: string
          required: true
        - in: query
          name: codice_fiscale
          schema:
            type: string
        - in: query
          name: descrizione
          schema:
            type: string
        - in: query
          name: mail
          schema:
            type: string
        - $ref: 'https://teamdigitale.github.io/openapi/parameters/v3.yaml#/fields'
      responses:
        <<: *common-responses
        '200':
          description: foo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ufficio'

  /amministrazione/{codice_ipa}/area_organizzativa_omogenea/{codice_aoo}:
    get:
      operationId: api.get_aoo_by_ipa
      parameters:
        - in: path
          name: codice_ipa
          required: true
          schema:
            type: string
        - in: path
          name: codice_aoo
          required: true
          schema:
            type: string
        - in: query
          name: descrizione
          schema:
            type: string
        - $ref: 'https://teamdigitale.github.io/openapi/parameters/v3.yaml#/fields'
      responses:
        <<: *common-responses
        '200':
          description: foo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AOO'

  /amministrazione/{codice_ipa}/aree_organizzative_omogenee:
    get:
      operationId: api.list_aoo
      parameters:
        - in: path
          name: codice_ipa
          required: true
          schema:
            type: string
        - in: query
          name: codice_aoo
          schema:
            type: string
        - in: query
          name: descrizione
          schema:
            type: string
        - $ref: 'https://teamdigitale.github.io/openapi/parameters/v3.yaml#/fields'
        - $ref: https://teamdigitale.github.io/openapi/parameters/v3.yaml#/limit
      responses:
        <<: *common-responses
        '200':
          description: foo
          content:
            application/json:
              schema:
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/AOO'


  /uffici:
    get:
      operationId: api.list_uffici
      parameters:
        - in: query
          name: codice_ipa
          schema:
            type: string
        - in: query
          name: codice_univoco_ufficio
          schema:
            type: string
        - in: query
          name: codice_fiscale
          schema:
            type: string
        - in: query
          name: descrizione
          schema:
            type: string
        - in: query
          name: mail
          schema:
            type: string
        - $ref: 'https://teamdigitale.github.io/openapi/parameters/v3.yaml#/fields'
        - $ref: 'https://teamdigitale.github.io/openapi/parameters/v3.yaml#/limit'
      responses:
        <<: *common-responses
        '200':
          description: foo
          content:
            application/json:
              schema:
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Ufficio'
  /ufficio/{codice_univoco_ufficio}:
    get:
      operationId: api.get_ufficio
      parameters:
      - in: path
        name: codice_univoco_ufficio
        required: true
        schema:
          type: string
      responses:
        <<: *common-responses
        '200':
          description: foo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ufficio'
components:
  schemas:
    Problem:
      $ref: 'https://teamdigitale.github.io/openapi/schemas/problem.yaml#/Problem'
    Amministrazione:
      properties:
        location:
          $ref: '#/components/schemas/Location'
        responsabile:
          $ref: '#/components/schemas/Responsabile'
        servizi:
          type: array
          items:
            $ref: '#/components/schemas/Servizio'
        codice_ipa:
          description: cod_amm
          type: string
        codice_fiscale:
          description: CF
          type: string
        descrizione:
          description: des_amm
          type: string
        mail:
          type: array
          items:
            type: string
            format: email
        categoria:
          type: string
        tipologia:
          type: string
        sito_istituzionale:
          type: string
          format: url
        contatti:
          properties:
            mail:
              type: string
              format: email
            tipo:
              type: string
              enum:
              - pec
              - altro
        data_accreditamento:
          description: TODO
          type: string
          format: date
    Responsabile:
      properties:
        nome_proprio:
          description: nome_resp
          type: string
        cognome:
          description: cogn_resp
          type: string
        titolo:
          description: titolo_rep
          type: string
    Location:
      properties:
        indirizzo:
          type: string
        cap:
          type: string
        comune:
          type: string
        provincia:
          type: string
        regione:
          type: string
    Ufficio:
      properties:
        codice_ipa: {type: string}
        codice_univoco_ufficio: {type: string}
    Servizio:
      properties:
        nome:
          type: string
        fruibilita:
          type: string
        descrizione:
          type: string
        progressivo:
          type: string
        mail:
          type: string
        url:
          type: string
    AOO:
      properties:
        codice_ipa: {type: string}

  responses:
    # Predefined error codes for this API
    400BadRequest:
      $ref: 'https://teamdigitale.github.io/openapi/responses/v3.yaml#/400BadRequest'
    404NotFound:
      $ref: 'https://teamdigitale.github.io/openapi/responses/v3.yaml#/404NotFound'
    429TooManyRequests:
      $ref: 'https://teamdigitale.github.io/openapi/responses/v3.yaml#/429TooManyRequests'
    503ServiceUnavailable:
      $ref: 'https://teamdigitale.github.io/openapi/responses/v3.yaml#/503ServiceUnavailable'
    default:
      $ref: 'https://teamdigitale.github.io/openapi/responses/v3.yaml#/default'